-- SUPABASE SCHEMA — PROJECT FOTOGRAFER
-- Jalankan di Supabase SQL Editor.
-- Setelah tabel dibuat, buat 1 akun admin melalui Auth lalu set is_admin = true.

create type public.access_role as enum ('NONE','FEMALE','MALE','PUBLIC');
create type public.account_status as enum ('PENDING','APPROVED','REJECTED','REVOKED');
create type public.request_status as enum ('PENDING','APPROVED','REJECTED');

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  access_role public.access_role not null default 'NONE',
  status public.account_status not null default 'PENDING',
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.access_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  applicant_name text not null,
  requested_role public.access_role not null,
  status public.request_status not null default 'PENDING',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  title text not null,
  access_role public.access_role not null,
  display_url text not null,
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.access_requests enable row level security;
alter table public.photos enable row level security;

-- Helper: current user is admin.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true);
$$;

create policy "users read own profile" on public.profiles
for select to authenticated using (id = auth.uid() or public.is_admin());

create policy "users update own pending profile name only" on public.profiles
for update to authenticated using (id = auth.uid())
with check (id = auth.uid());

create policy "admins update profiles" on public.profiles
for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "users create own access request" on public.access_requests
for insert to authenticated with check (user_id = auth.uid());

create policy "users read own requests" on public.access_requests
for select to authenticated using (user_id = auth.uid() or public.is_admin());

create policy "admins review requests" on public.access_requests
for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- Photos: only approved users may read metadata matching their role.
create policy "approved users read allowed photos" on public.photos
for select to authenticated
using (
  is_published = true
  and (
    access_role = 'PUBLIC'
    or exists(
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.status = 'APPROVED'
        and p.access_role = public.photos.access_role
    )
  )
);

-- Admin can manage photo metadata.
create policy "admins manage photos" on public.photos
for all to authenticated
using (public.is_admin()) with check (public.is_admin());

-- Automatically create a profile when a new Auth user registers.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles(id) values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- IMPORTANT:
-- After creating your own admin Auth account, run:
-- update public.profiles set is_admin = true, status='APPROVED', access_role='PUBLIC'
-- where id = 'UUID_AKUN_ADMIN';
